<?php
include('includes/header.php');
include('includes/navbar.php');
?>

<div class="aboutus-parent">
    <div class="aboutus">
        <div>
            <h1>
                OUR SERVICES

            </h1>
            <p>
                <b> Connect U Solar</b> provides a number of quality solar services that will suit your requirement, for both residential & commercial needs. <br>
                <b>IT’S YOUR TURN TO BENEFIT FROM OUR OFFERS!</b>

            </p>
        </div>
        <div>
            <img src="imgs/services.PNG" alt="">
        </div>
    </div>
</div>

<div class="scrol-down">
    FIND OUT MORE
    <i class="bi bi-caret-down-fill"></i>
</div>

<div class="presentation">
    <div class="picture with-border services">
        <p>RESIDENTIAL <br>
            <span>SOLAR</span>

        </p>
        <img src="imgs/services2.jpg" alt="">
    </div>
    <div class="txt ">
        <p>
            An average Australian household consumes 18kw per day. Based on current rates of 0.33c per kilowatt, households could be spending over $2,000 a year in electricity. By installing a solar panel system within your home, you could save between 25% – 40% on your yearly electricity usage.
            By investing in solar, you will be able to combat the rising cost of living by producing your own energy to run your household. It will also reduce your carbon footprint on the planet and furthermore any additional energy produced and not utilised can be sold back to your energy provider or credited onto your next bill.

        </p>
    </div>
</div>

<div class="presentation  ">

    <div class="txt ">
        <p>
            Energy providers offer a feed-in tariff for any additional energy produced and not consumed. The rate varies depending on the energy retailer and should be assessed based on the following variables :
        <ul>
            <li>
                Feed-in tariff rate.
            </li>
            <li>
                Cost of energy.
            </li>
            <li>
                Daily supply charge.
            </li>
        </ul>
        Other T&Cs including discounts for paying on time.
        Our team will design a custom solar system specifically to suit your needs and household requirements.

        </p>
    </div>
    <div class="picture with-border services right">
        <img src="imgs/services3.png" alt="">
    </div>
</div>

<div class="presentation  ">
    <div class="picture with-border services">
        <p>
            BATTERY <br>
            <span>STORAGE</span>

        </p>
        <img src="imgs/services3.jpg" alt="">
    </div>
    <div class="txt ">
        <p>
        <h1>HOW DOES A BATTERY SYSTEM WORK?</h1>
        A solar battery system stores all of the excess energy generated by your solar panels to then be utilised at peak periods during the day, at night or in the event of a power outage. You will have an integrated smart system to monitor when your energy consumption is in excess, so that your generated energy will now both power your home at the same time as storing your excess energy which would usually have gone to the grid for a lesser economical rate.
        </p>
    </div>
</div>


<div class="presentation  ">

    <div class="txt ">
        <p>
            Solar power has become the greatest source of renewable energy for both residential and commercial entities. Why is this so?
        <ul>
            <li>
                It minimises the impact & influence of rising electricity rates
            </li>
            <li>
                You will have the ability to produce your own energy, reducing the consumption from energy retailers
            </li>
            <li>

                Cost effective with energy-draining appliances
            </li>
            <li>
                Surplus energy can be stored and utilised when required or sold back to energy retailers
            </li>
            <li>
                Take advantage of an uninterrupted energy
            </li>
            <li>
                supply. Battery storage instantly powers the home in the case of a power outage
            </li>
            <li>
                Long term investment & asset for your home or commercial entity.
            </li>


        </ul>
        </p>
    </div>
    <div class="picture with-border services right">
        <img src="imgs/services4.png" alt="">
    </div>
</div>

<div class="presentation  ">
    <div class="picture with-border services">
        <img src="imgs/services5.png" alt="">
    </div>
    <div class="txt ">
        <p>
        <h1>HOW MUCH ENERGY COULD YOU SAVE WITH THIS SYSTEM?</h1>
        You could reduce your grid electricity consumption by 80% with a solar and battery storage solution. This estimate is based on standard system installation and may vary dependant on on your actual individual circumstances.
        Connect U Solar will conduct an assessment on your home or business. We will design a custom solar system & storage solution to specifically suit your needs and requirements. <br>
        Our dedicated team of industry experts will guide you through the variety of options available to ensure you are completely satisfied with the end result.

        </p>
    </div>
</div>

<div class="presentation  " id="residencial">

    <div class="txt ">
        <p>
            By investing in a commercial solar system, the business will now be able to produce its own electricity to power the commercial enterprise. Energy bills will be dramatically reduced or even eliminated, this is dependent on the type of solar and battery storage system installed. <br>
            Our team is experienced in all facets of commercial solar projects. Our team of experts have a diverse range of specialist skills. Every project is executed to the highest standards to ensure maximum efficiency and longevity of the solar panel system.

        </p>
    </div>
    <div class="picture with-border services right">
        <p>
            COMMERCIAL <br>
            <span>SOLAR</span>

        </p>
        <img src="imgs/services6.png" alt="">
    </div>
</div>

<div class="presentation  " id="comercial">
    <div class="picture with-border services">
        <img src="imgs/services7.jpg" alt="">
    </div>
    <div class="txt ">
        <p>
        <h1>WHY SHOULD YOUR BUSINESS INVEST IN COMMERCIAL SOLAR?</h1>
        <ul>
            <li>
                Immediately reduce operating expenses.

            </li>
            <li>
                High investment returns.

            </li>
            <li>
                Increased operational agility & dynamics.

            </li>
            <li>
                Increased sustainability & positive public. relations.

            </li>
            <li>
                Reduce pollution & carbon emissions
            </li>
            <li>
                Reduce business risk & increases business assets.

            </li>
        </ul>
        </p>
    </div>
</div>
<div class="presentation  " id="batery">

    <div class="txt ">
        <p>
        <h1>
            GO GREEN & SAVE MONEY $$

        </h1>
        Generating electricity with solar power means that your organisation uses less fossil fuels and reduces greenhouse gas emissions. Solar power is a renewable clean power source that is available every day of the year, even on cloudy days.
        Make a significant difference to the planet and dramatically reduce your commercial energy expenses by installing a solar panel system within your business.

        </p>
    </div>
    <div class="picture  services right">
        <img src="imgs/services8.PNG" alt="">
    </div>
</div>

<div class="presentation  " id="electric">
    <div class="picture with-border services">
        <p>
            ELECTRICAL <br>
            <span>SERVICES</span>

        </p>
        <img src="imgs/services9.jpg" alt="">
    </div>
    <div class="txt ">
        <p>
            Connect U Solar offers a wide range of solar panels systems to work within your budget, providing you with the highest quality components and producing the best performance for the life of your investment.
            Not only do we specialise in solar installations, Connect U Solar also has highly skilled and experienced electricians to assist you with all of your electrical needs. There’s no job too big or too small for our team. Looking for a trusted licensed electrician? You’re in good hands with Connect U Solar.

        </p>
    </div>
</div>

<div class="benifits" id="benifits">
    <h1>
        YOU CAN BENEFIT FROM OUR SOLAR SERVICES ANYTIME

    </h1>
    <div class="content">
        <div class="parent">
            <div class="bene-img">
                <img src="imgs/benifits1.png" alt="">
                <p>SOLAR <br> <span>MAINTENANCE</span> </p>
            </div>
            <p>
                We will help to connect with CEC certified installers for the maintenance of your solar panels.
            </p>
            <button>
                GET A QUOTE
            </button>
        </div>
        <div class="parent">
            <div class="bene-img">
                <img src="imgs/binifits2.png" alt="">
                <p>SOLAR <br> <span>INSTALLATION</span></p>
                


            </div>

            <p>
                Our experienced team of installers are fully qualified working in a range of residential and commercial environments.

            </p>
            <button>
                GET A QUOTE
            </button>
        </div>
        <div class="parent">
            <div class="bene-img">
                <img src="imgs/benifits3.jpg" alt="">
                <p>
                SOLAR <br> <span>CLEANING</span>


                </p>
            </div>
            <p>
                We clean your solar panels and we make sure to give you the best advice to keep your system in shape in all weather conditions.
            </p>
            <button>
                GET A QUOTE
            </button>
        </div>
    </div>

</div>

<?php
include('includes/contactus.php');
include('includes/footer.php');
include('includes/scripts.php');
?>